spring:
  application:
    name: service-directory

server:
  port: 9900 # Configure a port for your service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  